name: 20 - SCA

on:
  workflow_dispatch:
  workflow_call:

env:
  NETCORE_VERSION: '7.0.x'

jobs:
  sca:
    permissions:
      actions: read
      security-events: write
      id-token: write
      contents: read
      issues: write
      pull-requests: write
    strategy:
      fail-fast: false
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash
    name: SCA Dotnet Core project
    steps:
      - name: Checkout action
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.NETCORE_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Bash
        run: |
          echo ${{ secrets.SNYK_KEY}}

      - name: Run Snyk to check for vulnerabilities
        id: snyk_scan
        uses: snyk/actions/dotnet@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_KEY }}
        with:
          args: --sarif-file-output=snyk.sarif --file=PublicSolution.sln

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: snyk-report
          path: snyk.sarif
