name: ZAP Security Test

on: [push]

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build ./PublicHomePage -t tryggve-public:secret-scan

    - name: Run Secret Scanner
      run: |
        docker run -i --rm --name=deepfence-secretscanner \
        -v /var/run/docker.sock:/var/run/docker.sock \
        deepfenceio/deepfence_secret_scanner:2.0.0 \
        -image-name tryggve-public:secret-scan \
        --output json > secret-scan.json

    # Additional step to upload scan report to GitHub Actions artifacts, if needed
    - uses: actions/upload-artifact@v2
      with:
        name: scan-result
        path: scan-result.json